version: '4.0'

services:
  student-service:
    image: student_app_part1:latest
    ports:
    - "8081:8081"
    networks:
      - my_network


  reg-service:
    image: student_app_part2:latest
    ports:
      - "8082:8082"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge